# Import Library

In [4]:
# import library
from tensorflow import keras
import pandas as pd
import numpy  as np
import joblib
from tensorflow.keras.models import load_model

# Load Model

In [2]:
# load preprocessor
with open('preprocessor.pkl','rb') as file_1:
    preprocessor = joblib.load(file_1)

In [5]:
# load ANN model
model = load_model('sequen_imp_model.h5')

# Data Loading

In [6]:
df_infer = pd.read_csv('h8dsft_P2M1_inference_Fitri Octaviani.csv')

In [7]:
df_infer.head()

,Unnamed: 0,age,gender,region_category,membership_category,joined_through_referral,preferred_offer_types,medium_of_operation,internet_option,days_since_last_login,...,avg_transaction_value,avg_frequency_login_days,points_in_wallet,used_special_discount,offer_application_preference,past_complaint,complaint_status,feedback,churn_risk_score,joining_month
0,3479,59,M,Town,Gold Membership,No,Without Offers,Desktop,Wi-Fi,9,...,43978.54,0.0,789.60,Yes,Yes,No,Not Applicable,Too many ads,0,11
1,9414,26,F,City,Basic Membership,No,Gift Vouchers/Coupons,Desktop,Wi-Fi,16,...,33749.09,15.0,521.36,Yes,No,No,Not Applicable,No reason specified,1,4
2,15760,49,M,Town,Basic Membership,NaN,Without Offers,Desktop,Wi-Fi,7,...,41942.57,22.0,626.28,Yes,No,Yes,Unsolved,No reason specified,1,12
3,16668,21,F,Town,Basic Membership,Yes,Gift Vouchers/Coupons,Smartphone,Mobile_Data,19,...,47663.39,6.0,611.78,No,Yes,No,Not Applicable,Too many ads,1,3
4,17542,62,F,NaN,Basic Membership,Yes,Credit/Debit Card Offers,Smartphone,Wi-Fi,24,...,24566.68,16.0,672.93,Yes,No,No,Not Applicable,No reason specified,0,12

In [15]:
data_inf = df_infer.copy()
data_inf = df_infer.drop(['Unnamed: 0'],axis=1)
data_inf.head(2)

,age,gender,region_category,membership_category,joined_through_referral,preferred_offer_types,medium_of_operation,internet_option,days_since_last_login,avg_time_spent,avg_transaction_value,avg_frequency_login_days,points_in_wallet,used_special_discount,offer_application_preference,past_complaint,complaint_status,feedback,churn_risk_score,joining_month
0,59,M,Town,Gold Membership,No,Without Offers,Desktop,Wi-Fi,9,395.30,43978.54,0.0,789.60,Yes,Yes,No,Not Applicable,Too many ads,0,11
1,26,F,City,Basic Membership,No,Gift Vouchers/Coupons,Desktop,Wi-Fi,16,220.86,33749.09,15.0,521.36,Yes,No,No,Not Applicable,No reason specified,1,4

# Model Inference

In [10]:
# preprocess data before feedforwarding into the model
preprocessed_data = preprocessor.transform(data_inf)

In [11]:
# predict result
predictions = model.predict(preprocessed_data)

1/1 [==============================] - 0s 165ms/step

In [12]:
# convert prediction probability to each appropriate target class
pred = np.where(predictions>0.5,1,0)

In [16]:
# show data infer + prediction
data_inf['churn_risk_score'] = pred
data_inf.head(2)

,age,gender,region_category,membership_category,joined_through_referral,preferred_offer_types,medium_of_operation,internet_option,days_since_last_login,avg_time_spent,avg_transaction_value,avg_frequency_login_days,points_in_wallet,used_special_discount,offer_application_preference,past_complaint,complaint_status,feedback,churn_risk_score,joining_month
0,59,M,Town,Gold Membership,No,Without Offers,Desktop,Wi-Fi,9,395.30,43978.54,0.0,789.60,Yes,Yes,No,Not Applicable,Too many ads,0,11
1,26,F,City,Basic Membership,No,Gift Vouchers/Coupons,Desktop,Wi-Fi,16,220.86,33749.09,15.0,521.36,Yes,No,No,Not Applicable,No reason specified,1,4